server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Since we are using VITE_API_URL injected by Render, we do not need Nginx to proxy /api requests.

    # Serve React SPA — all other routes go to index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache static assets aggressively
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}
